const DESCEND_DIFF = 'DESCEND_DIFF'
const INSERTION = 'INSERTION'
const DELETION = 'DELETION'
const SUBSTITUTION = 'SUBSTITUTION'
const PROPS_PATCH = 'PROPS_PATCH'

const DEL_PROP = 'DEL_PROP'
const UPD_PROP = 'UPD_PROP'

export {
	DESCEND_DIFF,
	INSERTION,
	DELETION,
	SUBSTITUTION,
	PROPS_PATCH,
	DEL_PROP,
	UPD_PROP
}
